version: '3.3'

services:
  app:
    image: node:alpine
    tty: true
    stdin_open: true
    container_name: server-make-py
    restart: always
    working_dir: /app
    depends_on: # Só garante que o container está de pé, mas não a aplicação
      - db
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    volumes:
      - ./:/app
  db:
    image: mysql:8.0.23
    container_name: db-make-py
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root